# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-08 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nhood', '0004_auto_20180807_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='user',
            new_name='owner',
        ),
    ]
