# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-08 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nhood', '0005_auto_20180808_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='Nhood.Profile'),
        ),
    ]
